### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by sebohans** [lubbertkramer/net.tweakers.homey#6]
Hi, great app!
Maybe it's an idea to make multi purpose rss reader.
Where I can make several devices with different rss feeds that i copy pasted in the device.
Or maybe it could be configured from the settings screen.
This way we wouldn't need a seperate app for every rss stream.
I would really like the wintersporters.nl rss stream in my homey
Just an idea!

**Comment by bvdbos** [comment]
There is a general RSS-reader already:
https://apps.athom.com/app/eu.jeroensomhorst.feedreader
